using System;
using System.Collections.Generic;
using System.IO;
using System.Security;
using System.Text;
using RFramework;

namespace UnityRFramework.Editor
{
    /// <summary>
    /// 生成 Config 行类型、URFC v2 Codec 和自动注册代码。
    /// </summary>
    public static class ConfigCodeGenerator
    {
        /// <summary>
        /// 生成一张 Config 表的完整 C# 代码。
        /// </summary>
        /// <param name="schema">配置表定义。</param>
        /// <returns>生成的 C# 源代码。</returns>
        public static string Generate(ConfigTableSchema schema)
        {
            if (schema == null)
            {
                throw new RFrameworkException("Config schema is invalid.");
            }

            ConfigFieldSchema idField = null;
            for (int i = 0; i < schema.Fields.Count; i++)
            {
                if (string.Equals(schema.Fields[i].Name, "Id", StringComparison.OrdinalIgnoreCase))
                {
                    idField = schema.Fields[i];
                    break;
                }
            }

            if (idField == null)
            {
                throw new RFrameworkException($"Config schema '{schema.TableName}' has no Id field.");
            }

            string indent = string.IsNullOrEmpty(schema.Namespace) ? string.Empty : "    ";
            StringBuilder builder = new StringBuilder(4096);
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("// 由 UnityRFramework Config 转换工具生成，请勿手动修改。");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine("using System;");
            builder.AppendLine("using System.Collections.Generic;");
            builder.AppendLine("using System.IO;");
            builder.AppendLine("using RFramework;");
            builder.AppendLine("using UnityEngine;");
            builder.AppendLine("using UnityRFramework.Runtime;");
            builder.AppendLine();

            if (!string.IsNullOrEmpty(schema.Namespace))
            {
                builder.Append("namespace ").Append(schema.Namespace).AppendLine();
                builder.AppendLine("{");
            }

            AppendXmlSummary(builder, indent, schema.TableName + " 配置行。");
            builder.Append(indent).AppendLine("[Serializable]");
            builder.Append(indent).Append("public sealed class ").Append(schema.RowTypeName).AppendLine();
            builder.Append(indent).AppendLine("{");
            for (int i = 0; i < schema.Fields.Count; i++)
            {
                ConfigFieldSchema field = schema.Fields[i];
                string comment = string.IsNullOrEmpty(field.Comment)
                    ? field.Name + " 字段。"
                    : field.Comment;
                AppendXmlSummary(builder, indent + "    ", comment);

                builder.Append(indent).Append("    public ").Append(field.CSharpTypeName).Append(' ')
                    .Append(field.Name).AppendLine(";");
                if (i + 1 < schema.Fields.Count)
                {
                    builder.AppendLine();
                }
            }

            builder.Append(indent).AppendLine("}");
            builder.AppendLine();
            AppendXmlSummary(builder, indent, schema.TableName + " 的 URFC v2 读取器。");
            builder.Append(indent).Append("internal sealed class ").Append(schema.RowTypeName)
                .AppendLine("BinaryCodec : IBinaryConfigCodec");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    /// <inheritdoc/>");
            builder.Append(indent).Append("    public Type RowType => typeof(")
                .Append(schema.RowTypeName).AppendLine(");");
            builder.AppendLine();
            builder.Append(indent).AppendLine("    /// <inheritdoc/>");
            builder.Append(indent).Append("    public uint TableId => 0x")
                .Append(schema.TableId.ToString("X8")).AppendLine("u;");
            builder.AppendLine();
            builder.Append(indent).AppendLine("    /// <inheritdoc/>");
            builder.Append(indent).Append("    public ulong SchemaHash => 0x")
                .Append(schema.SchemaHash.ToString("X16")).AppendLine("UL;");
            builder.AppendLine();
            builder.Append(indent).AppendLine("    /// <inheritdoc/>");
            builder.Append(indent).AppendLine("    public object ReadTable(BinaryReader reader, int rowCount)");
            builder.Append(indent).AppendLine("    {");
            builder.Append(indent).AppendLine("        if (reader == null)");
            builder.Append(indent).AppendLine("        {");
            builder.Append(indent).AppendLine(
                "            throw new RFrameworkException(\"Binary config reader is invalid.\");");
            builder.Append(indent).AppendLine("        }");
            builder.AppendLine();
            builder.Append(indent).Append("        var table = new Dictionary<int, ")
                .Append(schema.RowTypeName).AppendLine(">(rowCount);");
            builder.Append(indent).AppendLine("        for (int i = 0; i < rowCount; i++)");
            builder.Append(indent).AppendLine("        {");
            builder.Append(indent).Append("            var row = new ").Append(schema.RowTypeName)
                .AppendLine();
            builder.Append(indent).AppendLine("            {");
            for (int i = 0; i < schema.Fields.Count; i++)
            {
                ConfigFieldSchema field = schema.Fields[i];
                builder.Append(indent).Append("                ").Append(field.Name).Append(" = ")
                    .Append(GetReadExpression(field.Kind));
                builder.AppendLine(i + 1 == schema.Fields.Count ? string.Empty : ",");
            }

            builder.Append(indent).AppendLine("            };");
            builder.Append(indent).Append("            if (table.ContainsKey(row.")
                .Append(idField.Name).AppendLine("))");
            builder.Append(indent).AppendLine("            {");
            builder.Append(indent).AppendLine("                throw new RFrameworkException(");
            builder.Append(indent).Append("                    $\"Binary config '")
                .Append(schema.RowTypeName).AppendLine("' contains duplicate \"");
            builder.Append(indent).Append("                    + $\"Id '{row.")
                .Append(idField.Name).AppendLine("}'.\");");
            builder.Append(indent).AppendLine("            }");
            builder.AppendLine();
            builder.Append(indent).Append("            table.Add(row.").Append(idField.Name)
                .AppendLine(", row);");
            builder.Append(indent).AppendLine("        }");
            builder.AppendLine();
            builder.Append(indent).AppendLine("        return table;");
            builder.Append(indent).AppendLine("    }");
            builder.Append(indent).AppendLine("}");
            builder.AppendLine();
            AppendXmlSummary(builder, indent, schema.TableName + " Codec 自动注册入口。");
            builder.Append(indent).Append("internal static class ").Append(schema.RowTypeName)
                .AppendLine("BinaryCodecRegistration");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine(
                "    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]");
            builder.Append(indent).AppendLine("    private static void RegisterRuntime()");
            builder.Append(indent).AppendLine("    {");
            builder.Append(indent).Append("        BinaryConfigCodecRegistry.Register(new ")
                .Append(schema.RowTypeName).AppendLine("BinaryCodec());");
            builder.Append(indent).AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("#if UNITY_EDITOR");
            builder.Append(indent).AppendLine("    [UnityEditor.InitializeOnLoadMethod]");
            builder.Append(indent).AppendLine("    private static void RegisterEditor()");
            builder.Append(indent).AppendLine("    {");
            builder.Append(indent).AppendLine("        RegisterRuntime();");
            builder.Append(indent).AppendLine("    }");
            builder.AppendLine("#endif");
            builder.Append(indent).AppendLine("}");

            if (!string.IsNullOrEmpty(schema.Namespace))
            {
                builder.AppendLine("}");
            }

            return builder.ToString();
        }

        /// <summary>
        /// 仅在内容变化时写入生成代码。
        /// </summary>
        /// <param name="path">输出路径。</param>
        /// <param name="code">生成的 C# 代码。</param>
        /// <returns>发生实际写入时返回 true。</returns>
        public static bool WriteCodeIfChanged(string path, string code)
        {
            if (File.Exists(path)
                && string.Equals(File.ReadAllText(path, Encoding.UTF8), code, StringComparison.Ordinal))
            {
                return false;
            }

            string directory = Path.GetDirectoryName(path);
            if (!string.IsNullOrEmpty(directory))
            {
                Directory.CreateDirectory(directory);
            }

            File.WriteAllText(path, code, new UTF8Encoding(false));
            return true;
        }

        private static string GetReadExpression(ConfigFieldKind kind)
        {
            switch (kind)
            {
                case ConfigFieldKind.Boolean: return "reader.ReadBoolean()";
                case ConfigFieldKind.Byte: return "reader.ReadByte()";
                case ConfigFieldKind.SByte: return "reader.ReadSByte()";
                case ConfigFieldKind.Int16: return "reader.ReadInt16()";
                case ConfigFieldKind.UInt16: return "reader.ReadUInt16()";
                case ConfigFieldKind.Int32: return "reader.ReadInt32()";
                case ConfigFieldKind.UInt32: return "reader.ReadUInt32()";
                case ConfigFieldKind.Int64: return "reader.ReadInt64()";
                case ConfigFieldKind.UInt64: return "reader.ReadUInt64()";
                case ConfigFieldKind.Single: return "reader.ReadSingle()";
                case ConfigFieldKind.Double: return "reader.ReadDouble()";
                case ConfigFieldKind.Decimal: return "reader.ReadDecimal()";
                case ConfigFieldKind.Char: return "(char)reader.ReadUInt16()";
                case ConfigFieldKind.String: return "BinaryFormatUtility.ReadUtf8String(reader, false)";
                default: throw new RFrameworkException($"Unsupported field kind '{kind}'.");
            }
        }

        private static string EscapeXml(string value)
        {
            return SecurityElement.Escape(value) ?? string.Empty;
        }

        private static void AppendXmlSummary(StringBuilder builder, string indent, string text)
        {
            const int TargetLineLength = 116;
            string normalized = (text ?? string.Empty).Replace('\r', ' ').Replace('\n', ' ');
            int contentLength = Math.Max(20, TargetLineLength - indent.Length - 4);
            builder.Append(indent).AppendLine("/// <summary>");
            for (int offset = 0; offset < normalized.Length; offset += contentLength)
            {
                int length = Math.Min(contentLength, normalized.Length - offset);
                builder.Append(indent).Append("/// ")
                    .AppendLine(EscapeXml(normalized.Substring(offset, length)));
            }

            if (normalized.Length == 0)
            {
                builder.Append(indent).AppendLine("///");
            }

            builder.Append(indent).AppendLine("/// </summary>");
        }
    }
}
